{% set version = "0.9.4.post1" %}
{% set name = "sanic-plugins-framework" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Sanic-Plugins-Framework-{{ version }}.tar.gz
  sha256: eea5b874c15255467c21acfb2e8b16b0e6bff5d11dffed698c63b2e759f3ec50

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - sanic >=18.12.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - spf

about:
  home: https://github.com/ashleysommer/sanicpluginsframework
  summary: A lightweight python library aimed at making it as simple as possible to build plugins for the Sanic Async HTTP Server
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - patricksnape
