{% set version = "0.9.4.post2" %}
{% set name = "sanic-plugins-framework" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Sanic-Plugins-Framework-{{ version }}.tar.gz
  sha256: 70226b4b455d876ffa3f75a4e5353407784ca4349fef4d7052853243e32400a7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - sanic >=18.12.0

test:
  imports:
    - spf

about:
  home: https://github.com/ashleysommer/sanicpluginsframework
  summary: A lightweight python library aimed at making it as simple as possible to build plugins for the Sanic Async HTTP Server
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - patricksnape
